### PR TITLE
Nz/4354 priorities scope

### LINKED ISSUE #4354: [Feature] State Priorities and Scope of APD page for MMIS APDs
### Description and related issues

MMIS APDs are going to have a new page called `State Priorities and Scope of APD` There will be 3 fields on this page.

Listed in order: 
- Medicaid Program and Priorities
- Medicaid Enterprise System Introduction
- Scope of APD

These fields will have inline validation based on Admin Check and cannot be blank.

### Behind the scenes changes:
* add a new file to actions/editApd and add the set methods to handle saving the new fields

Schema for new fields:
```json
...
statePrioritiesAndScope: {
  medicaidProgramAndPriorities: String,
  mesIntroduction: String,
  scopeOfAPD: String
},
...
```

Note: 
Adding this page to the side nav is out of scope for this ticket. We will add all side nav changes in #4371.

### Mockups or link to Figma
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=500%3A8747
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=414%3A10804 (Page is on far right)

### Acceptance criteria

| Given | When | Then |
| ----- | ---- | ---- |
| State Priorities and Scope of APD Page | On the page | Should have all the correct fields in the right order |
| State Priorities and Scope of APD Page | Admin check is on | If field is blank, there should be validation error message under text box |
| State Priorities and Scope of APD Page: Medicaid Program and Priorities field | Admin check is on | If field is blank, the validation error message should be: `Provide Medicaid Program and Priorities `|
| State Priorities and Scope of APD Page: Medicaid Enterprise System Introduction field | Admin check is on | If field is blank, the validation error message should be: `Provide a Medicaid Enterprise System Introduction `|
| State Priorities and Scope of APD Page: Scope of APD field | Admin check is on | If field is blank, the validation error message should be: `Provide an Overview of the APD's Scope `|

### This task is done when…

- [ ] all acceptance criteria are met
- [x] State Priorities and Scope of APD page has been created

### PR DESCRIPTION
**Pull request by Sun-Mountain**
Resolves #4354

### Description
Creating fields for the `State Priorities and Scope of APD` page, with validation, and connection to backend.

### Significant changes or possible side effects
- add fields to State Priorities and Scope of (MMIS) APD page
- add validation to fields
- connect fields to backend

### Automated test cases written

| Given | When | Then | Type (jest, tap, cypress) |
| ----- | ---- | ---- | ------------------------- |
| State Priorities and Scope of APD Page | On the page | Should have all the correct fields in the right order | cypress, jest |
| State Priorities and Scope of APD Page | Admin check is on | If field is blank, there should be validation error message under text box | jest |
| State Priorities and Scope of APD Page: Medicaid Program and Priorities field | Admin check is on | If field is blank, the validation error message should be: `Provide Medicaid Program and Priorities` | cypress |
| State Priorities and Scope of APD Page: Medicaid Enterprise System Introduction field | Admin check is on | If field is blank, the validation error message should be: `Provide a Medicaid Enterprise System Introduction` | cypress |
| State Priorities and Scope of APD Page: Scope of APD field | Admin check is on | If field is blank, the validation error message should be: Provide an Overview of the APD's Scope | cypress |

### Steps to manually verify this change

1. Create or go to an MMIS APD
2. Go to `State Priorities and Scope` in the side nav
3. Confirm all fields are there in right order
4. Can input text in all fields and it will save
5. On reload the text stays
6. When `Admin Check` is on and fields are blank, correct errors show

### This pull request is ready to code review when

- [x] Automated tests are updated (and all tests are passing)
- [x] New automated test cases are documented above
- [x] Pull request has been labeled, if applicable with feature, content, bug,
      tests, refactor
- [x] Associated OpenAPI documentation has been updated
- [ ] The experience passes a basic manual accessibility audit (keyboard nav,
      screenreader, text scaling) OR an exemption is documented

### This pull request is ready to test when

- [x] Code has been reviewed by someone other than the original author

### This pull request is ready to review when the QA has

- [x] Verified the functionality related to the change
- [x] Verified that the change works with Narrator on Windows
- [x] Verified that the change works with VoiceOver on Mac
- [x] Verified all updated pages with the WAVE tool
- [x] Verified tab and keyboard navigation functionality

### This pull request can be merged when

- [x] Design has approved the experience
- [x] Product has approved the experience

### CODE REVIEW

**Review by tbolt — APPROVED** [review]
Nice work

**Review by thetif — APPROVED** [review]
great work! Just one same optimization

**Review by mirano-darren — APPROVED** [review]
Looks good to me, nice work!
| Given | When | Then | Result |
| ----- | ---- | ---- |
| State Priorities and Scope of APD Page | On the page | Should have all the correct fields in the right order |
| State Priorities and Scope of APD Page | Admin check is on | If field is blank, there should be validation error message under text box | ✅ |
| State Priorities and Scope of APD Page: Medicaid Program and Priorities field | Admin check is on | If field is blank, the validation error message should be: `Provide Medicaid Program and Priorities `| ✅ |
| State Priorities and Scope of APD Page: Medicaid Enterprise System Introduction field | Admin check is on | If field is blank, the validation error message should be: `Provide a Medicaid Enterprise System Introduction `| ✅ |
| State Priorities and Scope of APD Page: Scope of APD field | Admin check is on | If field is blank, the validation error message should be: `Provide an Overview of the APD's Scope `| ✅ |
| State Priorities and Scope of APD Page | Testing continue and back buttons | Continue navigates to Key Personnel and back navigates to APD Overview| ✅ |
| State Priorities and Scope of APD Page | Admin check is on then turned off | Validation messages disappear when admin check is turned off | ✅ |

**Review by jeromeleecms — COMMENTED** [review]
Just a couple questions:
1) When I click on these new fields in the admin check, it takes me to a blank screen. Shouldn't it take me to the new screen?
2) When I try to move to the export view, the system takes me to a blank screen. Is this the correct behavior for now?

**Comment by Sun-Mountain** [comment]
> Just a couple questions:
> 
> 1. When I click on these new fields in the admin check, it takes me to a blank screen. Shouldn't it take me to the new screen?
> 2. When I try to move to the export view, the system takes me to a blank screen. Is this the correct behavior for now? Looking at the other tickets, it looks like this will be taken care of in another ticket.

@jeromeleecms:

1. Fixed the path issue.
2. We have not connected the MMIS APD to an export view, I believe that will be handled in [4313](https://app.zenhub.com/workspaces/cms-eapd-5a3823ad3659e94d8ee569be/issues/gh/enterprise-cmcs/eapd/4313)

**Review by jeromeleecms — APPROVED** [review]
Looks good! Thank you.

**Review by SGilliamA1M — APPROVED** [review]
Looks good.

**Pull request merged**
