### PR TITLE
4474 Executive Summary update for MMIS

### LINKED ISSUE #4474: [Feature] Executive Summary update for MMIS
### Description and related issues
Update the Program Budget Tables for MMIS to display the MMIS DDI Costs and MMIS M&O Costs tables.

### Mockups or link to Figma
Design #4450
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=2663%3A17558&t=5f6USvbNWlqCGlL2-3

### Behind the scene changes
The Budget Calculations will have to be updated to calculate the values for the MMIS DDI costs and MMIS M&O costs. The MMIS Budget model will need to be updated to store the new calculations. Sum costs by Category/MMIS DDI and M&O by split type/FFY; see sumMMISbyFFP for an example of how to do this. If all of the costs in the MMIS M&O Costs or MMIS DDI Costs table are $0, then hide the table. 

### Acceptance criteria

- [x] Add the tables to the Program Budget Table
- [x] the M&O table is hidden if all of its values are $0
- [x] the DDI table is hidden if all of it's values are $0

### Testing criteria

| Given | When | Then | Covered |
| ----- | ---- | ---- | ------- |
|A MMIS APD|On the Executive Summary Page|MMIS DDI costs and M&O costs table are present|(Add a checkmark here when covered)|
|A MMIS APD|On the Executive Summary Page, Funding percentage is changed|Tables should be updated according to the change |  |
|A MMIS APD|On the Executive Summary Page|If there is 0 M&O Costs for all FFY, the M&O table should be hidden|  |
|A MMIS APD|On the Executive Summary Page|If there is 0 DDI Costs for all FFY, the DDI Table should be hidden|  |
|A MMIS APD|On the Executive Summary Page|Page accounts for APDs with zero activities|  |
|A MMIS/HITECH APD|On the Executive Summary Page|If a FFY is deleted, that year is removed from each section and the budget tables. NOTE: Possibly not testable since we can't delete FFYs in MMIS APDs yet |  |
|A MMIS/HITECH APD|On the Executive Summary Page|If a FFY is added, that year is added to each section and the budget tables.  |  |
|A HITECH APD|On the Executive Summary page|DDI and M&O cost tables should not appear| |

### PR DESCRIPTION
**Pull request by tbolt**
Resolves #4474 

### Description
Updates MMIS Executive Summary - Program Budget Tables to be split out by DDI and M&O

### Chromatic Link
https://www.chromatic.com/pullrequest?appId=61d5b948cf6f17003a12bf77&number=4636&view=activity

### Significant changes or possible side effects
None noted

### Automated test cases written
Jest test for verifying rendering with valid budget and budget with 0 totals

| Given | When | Then | Type (jest, tap, cypress) |
| ----- | ---- | ---- | ------------------------- |
| an MMIS APD | viewing the Program Budget tables with all $0 totals | tables do not render | jest |
| an MMIS APD | viewing the Program Budget tables with a valid sample budget | tables render correctly | jest |

### Steps to manually verify this change
1. Login to a HITECH APD and verify no changes to existing Program Budget tables (in executive summary)
2. Login to a MMIS APD and verify new tables are present in Executive Summary
3. Verify tables match design spec

### This pull request is ready to code review when

- [x] Automated tests are updated (and all tests are passing)
- [x] New automated test cases are documented above
- [x] Chromatic link added above
- [x] Pull request has been labeled, if applicable with feature, content, bug,
      tests, refactor
- [ ] Associated OpenAPI documentation has been updated
- [ ] The experience passes a basic manual accessibility audit (keyboard nav,
      screenreader, text scaling) OR an exemption is documented

### This pull request is ready to test when

- [ ] Code has been reviewed by someone other than the original author

### This pull request is ready to review when QA has

- [ ] Verified the functionality related to the change
- [ ] Verified that the change works with Narrator on Windows
- [ ] Verified that the change works with VoiceOver on Mac
- [ ] Verified all updated pages with the WAVE tool
- [ ] Verified tab and keyboard navigation functionality

### This pull request can be merged when

- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by thetif — APPROVED** [review]
I was wondering if there was any way to make the column widths a little more fixed so that the headers line up a little better, but that's mostly nitpicking.

Code looks great though!

**Review by Sun-Mountain — APPROVED** [review]
🚀

**Comment by tbolt** [comment]
@thetif Im not sure of a great way to improve it. Fixing the width of any of the columns could be problematic because they are fluid based on the contents (ie. $0 is narrow vs. $1,500,000 is much wider). Making the table headers aligned right (vs. previously they were aligned left) does seem to help though. Here is what that looks like-
Screenshot 2023-04-04 at 9 43 52 AM

Curious what @akuas @SGilliamA1M think as well

**Review by amyd11 — APPROVED** [review]
Nice work! Everything looks good

**Comment by akuas** [comment]
@tbolt I will need to ruminate on this for a bit. I'll get back to you later.

**Comment by akuas** [comment]
How about this? Instead of putting the federal and state side by side horizontally, We can put federal above state, contained by the ffy. If this works, I could design it.

**Comment by akuas** [comment]
How about this? Instead of putting the federal and state side by side horizontally, We can put federal above state, contained by the ffy. If this works, I could design it.

**Comment by akuas** [comment]
@tbolt Hey, @jeromeleecms said in standup that it is fine if the width overflows in the builder as long as it looks fine when users export it. So, no redesign is needed now, if Im understanding it right.

**Review by mirano-darren — APPROVED** [review]
Looks good to me!
| Given | When | Then | Covered |
| ----- | ---- | ---- | ------- |
|A MMIS APD|On the Executive Summary Page|MMIS DDI costs and M&O costs table are present| ✅ | 
|A MMIS APD|On the Executive Summary Page, Funding percentage is changed|Tables should be updated according to the change | ✅  |
|A MMIS APD|On the Executive Summary Page|If there is 0 M&O Costs for all FFY, the M&O table should be hidden| ✅  |
|A MMIS APD|On the Executive Summary Page|If there is 0 DDI Costs for all FFY, the DDI Table should be hidden| ✅  |
|A MMIS APD|On the Executive Summary Page|Page accounts for APDs with zero activities| ✅  |
|A MMIS/HITECH APD|On the Executive Summary Page|If a FFY is deleted, that year is removed from each section and the budget tables. NOTE: Possibly not testable since we can't delete FFYs in MMIS APDs yet |✅   |
|A MMIS/HITECH APD|On the Executive Summary Page|If a FFY is added, that year is added to each section and the budget tables.  |  ✅ |
|A HITECH APD|On the Executive Summary page|DDI and M&O cost tables should not appear| ✅ |

**Comment by jeromeleecms** [comment]
@tbolt 

Looks like data from Key Personnel is still being added to the Executive Summary - was that fixed elsewhere? 

image

Also, in the admin check, I'm seeing these entries (are they related to this PR)?

image

Everything else looks awesome!

**Pull request merged**
