### PR TITLE
4589 [Feature] Create a fake state for testing on Staging and Production

### LINKED ISSUE #4589: [Feature] Create a fake state for testing on Staging and Production
### Description and related issues
Create a fake state that is only visible to the team, that can be used to test features on Staging and Production without interrupting state users. Once this has been created, update the test APDs in Staging to be associated with this state. Update the seeds to use this state. Update existing shared user accounts and team member accounts to have access to this state.

The fake State Name shall forever be known as "New Apdland" with an abbreviation of "NA." Pronounced "New Ap-dland"

### Behind the scene changes

**Feature flags-**
Create a feature flag that we can add specific users to. Add shared users and team member usernames to this flag (NOT including norole and norolemfa).

### Acceptance criteria

- [ ] specific users will be able to request access to a Test state
- [ ] all other users will not see this Test state as an option
- [ ] existing Staging APDs are associated with this Test state
- [ ] existing shared and team member users are associated with the Test state
- [ ] seeds are updated to add to this state

### Testing criteria

| Given | When | Then | Covered |
| ----- | ---- | ---- | ------- |
|  the norole user  | requesting access to a state | they should see the test state | cypress |
|  the betauser user  | requesting access to a state | they should not see the test state | cypress |

### PR DESCRIPTION
**Pull request by thetif**
Resolves #4589 

### Description
Added two flags
1) support-state-available - for users that should have access to New Apdland
2) support-team - for users that should have sys admin permissions

### Significant changes or possible side effects
Definitely affects logging in and changing states

### Automated test cases written

| Given | When | Then | Type (jest, tap, cypress) |
| ----- | ---- | ---- | ------------------------- |

### Steps to manually verify this change

1.
2.
3.

### This pull request is ready to code review when

- [ ] Automated tests are updated (and all tests are passing)
- [ ] New automated test cases are documented above
- [ ] Chromatic link added above
- [ ] Pull request has been labeled, if applicable with feature, content, bug,
      tests, refactor
- [ ] Associated OpenAPI documentation has been updated
- [ ] The experience passes a basic manual accessibility audit (keyboard nav,
      screenreader, text scaling) OR an exemption is documented

### This pull request is ready to test when

- [ ] Code has been reviewed by someone other than the original author

### This pull request is ready to review when QA has

- [ ] Verified the functionality related to the change
- [ ] Verified that the change works with Narrator on Windows
- [ ] Verified that the change works with VoiceOver on Mac
- [ ] Verified all updated pages with the WAVE tool
- [ ] Verified tab and keyboard navigation functionality

### This pull request can be merged when

- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by tbolt — APPROVED** [review]
Nice work

**Review by amyd11 — COMMENTED** [review]
Nice job working through all the set up for this!

**Review by amyd11 — APPROVED** [review]

**Review by mirano-darren — APPROVED** [review]
Looks good to me! New Apdland 😄 
| Given | When | Then | Covered |
| ----- | ---- | ---- | ------- |
|  the norole user  | requesting access to a state | they should see the test state | ✅ |
|  the betauser user  | requesting access to a state | they should not see the test state | ✅ |

**Review by stephanieboydcms — APPROVED** [review]

**Review by jeromeleecms — APPROVED** [review]
Welcome New Apdland.

**Pull request merged**
