### PR TITLE
Tbolt/4523 Dont allow blank strings in text input fields

### LINKED ISSUE #4523: [Feature] Add trim() to all string validation in joi
### Description and related issues
Validation should not allow strings to be just whitespace. Add .trim() to all of the string validation in common/schema to prevent this.

https://joi.dev/api/?v=17.7.0#stringtrimenabled

### Acceptance criteria

- [ ] every Joi.string() object includes a .trim() function to remove leading and trailing whitespace from the string

### Testing criteria

| Given | When | Then | Covered |
| ----- | ---- | ---- | ------- |
| A string with just whitespace | validation runs | it fails validation |         |
| A string with leading whitespace and text | validation runs | it passes | |
| A string with text and trailing whitespace | validation runs | it passes | |

### PR DESCRIPTION
**Pull request by tbolt**
Resolves #4523 

### Description
This updates all of the validations and related code to make empty strings not pass the validation

### Automated test cases written
Related tests updated to work with the new change

### Steps to manually verify this change

1. Create both types of APDs
2. Verify that for all text input fields (including rich text) you can enter blank spaces but it won't pass the validation or admin check

### This pull request is ready to code review when

- [x] Automated tests are updated (and all tests are passing)
- [x] New automated test cases are documented above
- [x] Pull request has been labeled, if applicable with feature, content, bug,
      tests, refactor
- [ ] Associated OpenAPI documentation has been updated
- [ ] The experience passes a basic manual accessibility audit (keyboard nav,
      screenreader, text scaling) OR an exemption is documented

### This pull request is ready to test when

- [x] Code has been reviewed by someone other than the original author

### This pull request is ready to review when the QA has

- [ ] Verified the functionality related to the change
- [ ] Verified that the change works with Narrator on Windows
- [ ] Verified that the change works with VoiceOver on Mac
- [ ] Verified all updated pages with the WAVE tool
- [ ] Verified tab and keyboard navigation functionality

### This pull request can be merged when

- [x] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by amyd11 — APPROVED** [review]
Pretty straightforward & works as expected

**Comment by mirano-darren** [comment]
Works for HITECH, but not for mmis-exclusive rich text fields

**Comment by mirano-darren** [comment]
Looks good to me! These test cases were tested on input fields and TinyMCE fields
| Given | When | Then | Covered |
| ----- | ---- | ---- | ------- |
| A string with just whitespace | validation runs | it fails validation |✅|
| A string with leading whitespace and text | validation runs | it passes | ✅  |
| A string with text and trailing whitespace | validation runs | it passes | ✅  |

**Review by mirano-darren — APPROVED** [review]

**Review by SGilliamA1M — APPROVED** [review]
@tbolt - checked each field and the changes look good. Great job!

**Comment by tbolt** [comment]
@jeromeleecms I am not sure. I feel like it used to disappear so it might be worth making a small bug ticket for us to look into it more.

**Pull request merged**
