### PR TITLE
Fixed issue with adding and removing years breaking Key State Personnel

### LINKED ISSUE #4572: [Feature] Update getPatchesToAddYear and getPatchesToRemoveYear to handle changes to Key State Personnel
### Description and related issues
The Key State Personnel object has changed so the patches need to update for adding and removing years.

### Acceptance criteria

- [ ] update getPatchesToAddYear and getPatchesToRemoveYear to handle changes to Key State Personnel

### Testing criteria

| Given | When | Then | Covered |
| ----- | ---- | ---- | ------- |
|       |      |      |         |

### PR DESCRIPTION
**Pull request by thetif**
Resolves #4572 

### Description
When the updates were made the the key state personnel model, the methods that update the APD when an FFY is added or removed weren't updated, so it would break the Key State Personnel page when you changed the years and tried to go back. I just added the new fields to the add and remove methods.

### Automated test cases written

| Given | When | Then | Type (jest, tap, cypress) |
| ----- | ---- | ---- | ------------------------- |
| a HITECH APD | a year is added | it updates the key state personnel correctly | jest |
| a HITECH APD | a year is removed | it updates the key state personnel correctly | jest |
| a MMIS APD | a year is added | it updates the key state personnel correctly | jest |
| a MMIS APD | a year is removed | it updates the key state personnel correctly | jest |

### Steps to manually verify this change

1. Create an MMIS APD
2. Add a Key State Personnel
3. Add an FFY
4. Go back to Key State Personnel and make sure it updated correctly
5. Remove an FFY (the first one)
6. Go back to Key State Personnel and make sure it updated correctly

### This pull request is ready to code review when

- [x] Automated tests are updated (and all tests are passing)
- [x] New automated test cases are documented above
- [x] Pull request has been labeled, if applicable with feature, content, bug,
      tests, refactor

### This pull request is ready to test when

- [ ] Code has been reviewed by someone other than the original author

### This pull request is ready to review when the QA has

- [ ] Verified the functionality related to the change
- [ ] Verified that the change works with Narrator on Windows
- [ ] Verified that the change works with VoiceOver on Mac
- [ ] Verified all updated pages with the WAVE tool
- [ ] Verified tab and keyboard navigation functionality

### This pull request can be merged when

- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by tbolt — APPROVED** [review]
Looks good

**Review by amyd11 — APPROVED** [review]
I love diagrams- thanks for including this

**Review by mirano-darren — APPROVED** [review]
Bug squashed!

**Review by jeromeleecms — APPROVED** [review]
Looks like bug squashed. Good find and fix.

**Pull request merged**
