### PR TITLE
Tbolt/4602 Update help text on cost allocation and other funding page for MMIS

### LINKED ISSUE #4602: [Feature] Update help text on Cost Allocation and Other Funding
### Description and related issues

- Cost Allocation, change the 2nd line in the copy to 
> 2. Cost allocation formulas should be based on direct benefit to Medicaid.

- Other Funding Description, change the text to
> Provide a high-level description of funds that are not directly tied to the Medicaid grant. This funding may come from another federal source, another state agency, and/or donations or contributions from a third party such as payer and provider subscription fees. If other funds will be used to cover the State share tied to the Medicaid grant, please include a justification for this here.

- Other Funding Amount, change the text to
> Provide the total amount of funds not associated with the Medicaid grant (i.e. any cost allocated funding from all parties) and the amount from other funding that will will not be used for the State share of the Medicaid grant. This amount will be deducted from the total cost of the activity to calculate the total computable Medicaid cost for this activity.

### Mockups or link to Figma
Design ticket #3690
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=4769%3A20151&t=0wK3WJkwZFF2eXfZ-1

### Acceptance criteria

- [ ] Update the help text (only for MMIS)

### Test cases
| Given  | When | Then |
| ------------- | ------------- | ------------- |
| A HITECH APD  | on the Cost Allocation and Other Funding page  | Help text should not be updated  |
| A MMIS APD  | on the Cost Allocation and Other Funding page  | Help text should be updated  |

### PR DESCRIPTION
**Pull request by tbolt**
Resolves #4602 

### Description
Text updates on MMIS page for cost allocation and other funding

### Chromatic Link
N/A

### Significant changes or possible side effects
None

### Automated test cases written
No new test cases written. Existing tests updated to work with text changes.

### Steps to manually verify this change

1. Login and view HITECH APD and verify existing help text not impacted (covered by existing test)
2. Login and view MMIS APD and verify help text is according to specification

### This pull request is ready to code review when

- [x] Automated tests are updated (and all tests are passing)
- [x] New automated test cases are documented above
- [x] Chromatic link added above
- [x] Pull request has been labeled, if applicable with feature, content, bug,
      tests, refactor
- [x] Associated OpenAPI documentation has been updated
- [ ] The experience passes a basic manual accessibility audit (keyboard nav,
      screenreader, text scaling) OR an exemption is documented

### This pull request is ready to test when

- [ ] Code has been reviewed by someone other than the original author

### This pull request is ready to review when QA has

- [ ] Verified the functionality related to the change
- [ ] Verified that the change works with Narrator on Windows
- [ ] Verified that the change works with VoiceOver on Mac
- [ ] Verified all updated pages with the WAVE tool
- [ ] Verified tab and keyboard navigation functionality

### This pull request can be merged when

- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by Sun-Mountain — APPROVED** [review]
🚀

**Review by thetif — APPROVED** [review]
looks good

**Review by amyd11 — APPROVED** [review]

**Comment by mirano-darren** [comment]
Looks good to me! Let Ty know about one small typo I found. 
image

| Given  | When | Then | Result |
| ------------- | ------------- | ------------- | ------------- |
| A HITECH APD  | on the Cost Allocation and Other Funding page  | Help text should not be updated  | ✅ |
| A MMIS APD  | on the Cost Allocation and Other Funding page  | Help text should be updated  | ✅ |

**Review by mirano-darren — APPROVED** [review]

**Comment by tbolt** [comment]
@mirano-darren Resolved

**Review by jeromeleecms — APPROVED** [review]
Looks good!

**Review by SGilliamA1M — APPROVED** [review]
Changes look great!

**Pull request merged**
