### PR TITLE
4597 - [Feature] Display standard APD header on activities pages

### LINKED ISSUE #4597: [Feature] Display standard APD header on activities pages
### Description and related issues
The APD header is not being shown on the activities pages, but it should be shown on those pages as well.

### Acceptance criteria

- [x] the header displays on the activities pages

### PR DESCRIPTION
**Pull request by Sun-Mountain**
Resolves #4597 

### Description
The APD header is not being shown on the activities pages, but it should be shown on those pages as well.

### Chromatic Link
https://www.chromatic.com/build?appId=61d5b948cf6f17003a12bf77&number=1359

### Automated test cases written

| Given | When | Then | Type (jest, tap, cypress) |
| ----- | ---- | ---- | ------------------------- |
| Continue button test | running in e2e | will check for header on every page | cypress |

### Steps to manually verify this change

1. Open a new or existing apd
2. Go to an activity page
3. Ensure apd name header is present.

### This pull request is ready to code review when

- [x] Automated tests are updated (and all tests are passing)
- [x] New automated test cases are documented above
- [x] Chromatic link added above
- [x] Pull request has been labeled, if applicable with feature, content, bug,
      tests, refactor
- [ ] Associated OpenAPI documentation has been updated
- [x] The experience passes a basic manual accessibility audit (keyboard nav,
      screenreader, text scaling) OR an exemption is documented

### This pull request is ready to test when

- [x] Code has been reviewed by someone other than the original author

### This pull request is ready to review when QA has

- [x] Verified the functionality related to the change
- [ ] Verified that the change works with Narrator on Windows
- [ ] Verified that the change works with VoiceOver on Mac
- [ ] Verified all updated pages with the WAVE tool
- [x] Verified tab and keyboard navigation functionality

### This pull request can be merged when

- [x] Design has approved the experience
- [x] Product has approved the experience

### CODE REVIEW

**Review by thetif — APPROVED** [review]
looks great! One line of code changes and then three test files updated, love it 😄

**Review by amyd11 — APPROVED** [review]
Looks good to me!

**Review by tbolt — APPROVED** [review]

**Review by mirano-darren — APPROVED** [review]
Looks good to me! Well done 😄

**Review by SGilliamA1M — APPROVED** [review]
Changes look great!

**Review by jeromeleecms — APPROVED** [review]
Looks good!

**Pull request merged**
