### PR TITLE
updated assurance and compliance for mmis

### LINKED ISSUE #4473: [Feature] Update Assurances and Compliance to work with MMIS
### Description and related issues
MMIS had different Assurances than HITECH. It will probably be cleaner to create a new component and then make a wrapper that serves the correct component for the APD type.

Design ticket: #2983

Links for the Assurances and Compliance:
* Procurement Standards (Competition / Sole Source)
    * SMM, Part 11: https://www.cms.gov/Regulations-and-Guidance/Guidance/Manuals/Paper-Based-Manuals-Items/CMS021927.html
    * 45 CFR Part 95.615: https://www.ecfr.gov/cgi-bin/text-idx?SID=2cfd59b6ec7c0a6adf749237ebbd1ba1&mc=true&node=se45.1.95_1615&rgn=div8
    * 45 CFR Part 75.326: https://www.ecfr.gov/cgi-bin/text-idx?SID=d1d1ed46083496c2114c787af6f29afc&mc=true&node=pt45.1.75&rgn=div5#se45.1.75_1326
* Access to Records, Reporting, and Agency Attestations
    * 45 CFR Part 433.112 (b)(5)-(9): https://www.ecfr.gov/cgi-bin/text-idx?SID=8c677ad13ab6c202c5ae1ee1c1c0b487&mc=true&node=se42.4.433_1112&rgn=div8
    * 45 CFR Part 95.615: https://www.ecfr.gov/cgi-bin/text-idx?SID=2cfd59b6ec7c0a6adf749237ebbd1ba1&mc=true&node=se45.1.95_1615&rgn=div8
    * SMM Section 11267: https://www.cms.gov/Regulations-and-Guidance/Guidance/Manuals/Paper-Based-Manuals-Items/CMS021927.html
* Software & Ownership
    * 45 CFR 95.617: https://www.ecfr.gov/cgi-bin/text-idx?SID=2cfd59b6ec7c0a6adf749237ebbd1ba1&mc=true&node=se45.1.95_1617&rgn=div8
    * 42 CFR Part 431.300: https://www.ecfr.gov/current/title-42/chapter-IV/subchapter-C/part-431/subpart-F/section-431.300
    * 45 CFR Part 164: https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C/part-164
* IV&V
    * 45 CFR Part 95.626: https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-A/part-95/subpart-F/subject-group-ECFR8ea7e78ba47a262/section-95.626

### Mockups or link to Figma
https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=1383%3A12345&t=Rn8u9FYuQpsrRjvJ-1

### Behind the scene changes
The values are already being added to post.mmis.data.js (double check that the typo "SSM, Part 11" has been updated to "SMM, Part 11" under procurement). The values are also being stored in the database. No addition backend updates should be needed. Validation should already be set up too.

**Feature flags-**
This will be hidden behind the enableMMIS flag, but this part of the code does not need to be wrapped in it.

### Acceptance criteria

- [x] The frontend displays the old Assurances and Compliance page for HITECH APDs
- [x] The frontend displays the new Assurances and Compliance page for MMIS APDs
- [x] The MMIS Assurances and Compliance page matches the Figma above
- [x] Checking no, opens the explanation text area
- [x] Validation works when the Admin Check is on
   - [x] The user is required to select yes or no
   - [x] If no is selection, the user must put text in the text area
- [ ] clicking the error in admin check takes you to the Assurances and Compliance page

### Testing criteria

| Given | When | Then | Covered? |
| ----- | ---- | ---- | ------- |
|A MMIS APD|On the Assurances and Compliance page| Should have the following assurances listed in order: <br /> **Procurement Standards (Competition / Sole Source)** <br /> - SMM, Part 11 <br /> - 45 CFR Part 95.615 <br /> - 45 CFR Part 92.36 <br /> **Access to Records, Reporting and Agency Attestations** <br /> - 42 CFR Part 433.112(b)(5) - (9) <br /> - 45 CFR Part 95.615 <br /> - SMM Section 11267 <br /> **Software & Ownership Rights...** <br /> - 45 CFR Part 95.617 <br /> - 42 CFR Part 431.300 <br /> - 45 CFR Part 164 <br /> **Independent Verification and Validation (IV&V)** <br /> - 45 CFR Part 95.626  | (add checkmark here when covered) |
| A HITECH APD | On the Assurances and Compliance page | Nothing should change. Fields should be the same as before |  |
| A HITECH or MMIS APD | On the Assurances and Compliance page, answering "No" to any assurance | explanation text box opens |  |
| A HITECH or MMIS APD | On the Assurances and Compliance page, Admin Check is on | Should have a validation message if: <br /> - User does not select yes or no. Validation message should be **"Select yes or no"** <br /> - User answers "No" but explanation text is empty. Validation message should be **"Provide an explanation"** |  |
| A HITECH or MMIS APD | On the Assurances and Compliance page, Admin check is NOT on  | Validation messages should not appear | | 
| A HITECH or MMIS APD | On the Assurances and Compliance page  | All Hyperlinks to assurances should take the user to the correct assurance page | |
| A MMIS APD | On the Assurances and Compliance page, all filled out | Read only view should display correct values | |

### PR DESCRIPTION
**Pull request by thetif**
Resolves #4473 

### Description
Updated the Assurance and Compliance components to handle MMIS data. Removed some old code that creates citations on the front end if they don't already exist in the APD. This isn't needed any more because all of the APDs in staging and prod have assurance and compliance. They get added when you create and new APD. And it would be extra complicated to update it to handle the new types. Also created storybook stories.

### Automated test cases written

| Given | When | Then | Type (jest, tap, cypress) |
| ----- | ---- | ---- | ------------------------- |
| a MMIS APD | the Assurances and Compliance page is loaded | it renders correctly | jest |
| a MMIS APD | the Assurances and Compliance Read Only page is loaded | it renders correctly | jest |
| a user on the Assurances and Compliance page | the user sets an IV&V compliance | an action is dispatched to update the APD | jest |
| a user on the Assurances and Compliance page | the user sets an IV&V justification | an action is dispatched to update the APD | jest | 

### Steps to manually verify this change

1. open a MMIS APD
2. navigate to the Assurances and Compliance page
3. verify that the citation match the ones from the ticket
4. verify that all of the citations have a url
5. verify that the urls are valid
6. select Yes
7. select No and a text box should open
8. enter text in the text box
9. select Yes and the text box should disappear
10. select No on a citation and don't enter any text in the text box
11. leave a citation empty
12. turn on Admin Check
13. verify that you see an error message under the empty text box
14. verify that you see an error message under the empty citation
15. verify that you see the errors in the Admin Check panel
16. verify that entering text and making a selection make the error message go away
17. verify that the error messages went away in the Admin Check panel
18. open a HITECH APD
19. navigate to the Assurances and Compliance page
20. verify that the citations are different than they were for the MMIS APD

### This pull request is ready to code review when

- [x] Automated tests are updated (and all tests are passing)
- [x] New automated test cases are documented above
- [x] Pull request has been labeled, if applicable with feature, content, bug,
      tests, refactor

### This pull request is ready to test when

- [ ] Code has been reviewed by someone other than the original author

### This pull request is ready to review when the QA has

- [ ] Verified the functionality related to the change
- [ ] Verified that the change works with Narrator on Windows
- [ ] Verified that the change works with VoiceOver on Mac
- [ ] Verified all updated pages with the WAVE tool
- [ ] Verified tab and keyboard navigation functionality

### This pull request can be merged when

- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by amyd11 — APPROVED** [review]
Everything works as expected after creating a new MMIS APD!

At first I checked the one created with seed data and either we need to update the seed data or there was just some old data in the database in this environment. It looked like **45 CFR Part 92.36** was on the list instead of the desired "45 CFR Part 75.326". Also, some of the citations are just text and not links:
- 45 CFR Part 92.36
- 42 CFR Part 433.112(b)(5)-(9)
- 45 CFR Part 95.617

I just had the one question about the switch statement, but everything else looks great!

**Review by tbolt — APPROVED** [review]

**Comment by thetif** [comment]
@amyd11 great catch on the regulations, I went back and I think I got them all cleaned up.

**Review by amyd11 — APPROVED** [review]
Thanks for updating the seed files! Looks good ✅

**Comment by mirano-darren** [comment]
Looks good! 2 small changes that don't match with the Figma:

This should be 42, not 45. Link is still correct
image

Compliance and progress reports should be lowercase
image

**Comment by mirano-darren** [comment]
Looks good to me pending the 2 changes requested above!
| Given | When | Then | Result |
| ----- | ---- | ---- | ------- |
|A MMIS APD|On the Assurances and Compliance page| Should have the following assurances listed in order: <br /> **Procurement Standards (Competition / Sole Source)** <br /> - SMM, Part 11 <br /> - 45 CFR Part 95.615 <br /> - 45 CFR Part 92.36 <br /> **Access to Records, Reporting and Agency Attestations** <br /> - 42 CFR Part 433.112(b)(5) - (9) <br /> - 45 CFR Part 95.615 <br /> - SMM Section 11267 <br /> **Software & Ownership Rights...** <br /> - 45 CFR Part 95.617 <br /> - 42 CFR Part 431.300 <br /> - 45 CFR Part 164 <br /> **Independent Verification and Validation (IV&V)** <br /> - 45 CFR Part 95.626  | 🟨 See above comment |
| A HITECH APD | On the Assurances and Compliance page | Nothing should change. Fields should be the same as before | ✅  |
| A HITECH or MMIS APD | On the Assurances and Compliance page, answering "No" to any assurance | explanation text box opens | ✅  |
| A HITECH or MMIS APD | On the Assurances and Compliance page, Admin Check is on | Should have a validation message if: <br /> - User does not select yes or no. Validation message should be **"Select yes or no"** <br /> - User answers "No" but explanation text is empty. Validation message should be **"Provide an explanation"** | ✅  |
| A HITECH or MMIS APD | On the Assurances and Compliance page, Admin check is NOT on  | Validation messages should not appear | ✅  | 
| A HITECH or MMIS APD | On the Assurances and Compliance page  | All Hyperlinks to assurances should take the user to the correct assurance page | ✅  |
| A MMIS APD | On the Assurances and Compliance page, all filled out | Read only view should display correct values | 🟨 Export view still crashes |

**Comment by thetif** [comment]
@mirano-darren I doubled checked the list that Jerome sent me and I think the typo is in the design. The capitalization thing didn't change in this ticket. If you check staging the casing is the same, and it matches with the casing style of the other sections.

Procurement Standards (Competition / Sole Source)
* SMM, Part 11: https://www.cms.gov/Regulations-and-Guidance/Guidance/Manuals/Paper-Based-Manuals-Items/CMS021927.html
* 45 CFR Part 95.615: https://www.ecfr.gov/cgi-bin/text-idx?SID=2cfd59b6ec7c0a6adf749237ebbd1ba1&mc=true&node=se45.1.95_1615&rgn=div8
* 45 CFR Part 75.326: https://www.ecfr.gov/cgi-bin/text-idx?SID=d1d1ed46083496c2114c787af6f29afc&mc=true&node=pt45.1.75&rgn=div5#se45.1.75_1326

Access to Records, Reporting, and Agency Attestations
* 45 CFR Part 433.112 (b)(5)-(9): https://www.ecfr.gov/cgi-bin/text-idx?SID=8c677ad13ab6c202c5ae1ee1c1c0b487&mc=true&node=se42.4.433_1112&rgn=div8
* 45 CFR Part 95.615: https://www.ecfr.gov/cgi-bin/text-idx?SID=2cfd59b6ec7c0a6adf749237ebbd1ba1&mc=true&node=se45.1.95_1615&rgn=div8
* SMM Section 11267: https://www.cms.gov/Regulations-and-Guidance/Guidance/Manuals/Paper-Based-Manuals-Items/CMS021927.html

Software & Ownership
* 45 CFR 95.617: https://www.ecfr.gov/cgi-bin/text-idx?SID=2cfd59b6ec7c0a6adf749237ebbd1ba1&mc=true&node=se45.1.95_1617&rgn=div8
* 42 CFR Part 431.300: https://www.ecfr.gov/current/title-42/chapter-IV/subchapter-C/part-431/subpart-F/section-431.300
* 45 CFR Part 164: https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C/part-164

IV&V
* 45 CFR Part 95.626: https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-A/part-95/subpart-F/subject-group-ECFR8ea7e78ba47a262/section-95.626

**Review by mirano-darren — APPROVED** [review]
Looks good to me!

**Review by SGilliamA1M — APPROVED** [review]
Citations have been updated successfully for MMIS. Great job!

**Review by stephanieboydcms — APPROVED** [review]
Thank you for the review request.  Good to move forward @thetif

**Pull request merged**
