### PR TITLE
Tbolt/4371 mmis nav updates

### LINKED ISSUE #4371: [Dev] Update sidebar navigation and activity sections for MMIS APDs
Describe the task here and link or add dependencies to any applicable issues...

Updates to Nav Items:
- State Priorities and Scope of APD (only for MMIS)
- Activities
  - Analysis of Alternatives and Risks (only for MMIS)
  - Activity Schedule and Milestones // break out Activity Schedule from APD Overview and Milestones from Outcomes and Milestones (both HITECH and MMIS)
  - Conditions for Enhanced Funding (only for MMIS)
  - Outcomes and Metrics // rename from Outcomes and Milestones (for both HITECH and MMIS)
- Disaster Recovery Plan (only for MMIS)
- Remove Proposed Budget -> Quarterly Federal Share (mmis only)
- Remove Proposed Budget -> Estimated Quaterly Incentive Payments (mmis only)

Re-organize activity sections:
- Move Activity Schedule from Activity Overview to Activity Schedule and Milestones (for both HITECH and MMIS)
- Move Milestones from Outcomes and Milestones to Activity Schedule and Milestones (for both HITECH and MMIS)

Updates to admin check:
- Activity Schedule error should link to new location

Design ticket: #4357

Since some pages will be changing with MMIS APDs, we also need to update the sidebar navigation. 

[Figma](https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=1515%3A12934)
[List of MMIS Changes](https://docs.google.com/spreadsheets/d/1yCB-XfLO6QJL4iugFhoUHZWYJZ7IMtwBI8ZgtVilHmE/edit#gid=0)

Acceptance Criteria:
| Given  | When | Then |
| ------------- | ------------- | ------------- |
| Sidebar navigation  | interacting with the nav  | Each section/subsection should match the Figma  |
| Sidebar navigation  | clicking through the nav  | Key State Personnel, Results of Previous Activities, Activities, Proposed Budget, and Executive Summary sections should be expandable/collapsible   |
| Sidebar navigation  | clicking through the nav  | Each section/subsection should hyperlink to the correct page  |

### This task is done when...

- [ ] Sidebar navigation has been updated for MMIS
- [ ] APD sections have been re-arranged according to design

### PR DESCRIPTION
**Pull request by tbolt**
Resolves #4371 

### Description
Updates side nav to support different apdTypes: HITECH and MMIS

### Significant changes or possible side effects
* Navigation is updated to reflect different sections based on whether the apd is HITECH or MMIS type

### Automated test cases written

| Given | When | Then | Type (jest, tap, cypress) |
| ----- | ---- | ---- | ------------------------- |
| viewing an apd | its a MMIS apd | should show 4 new sections in the nav | jest |
| viewing an apd | its a HITECH apd | should not show 4 new sections in the nav | jest |

### Steps to manually verify this change
1. Select an APD with HITECH type (existing seed)
2. Verify the side nav is according to the original ticket / figma / google doc
3. Select and APD with MMIS type (existing seed)
4. Verify the side nav is according to the original ticket / figma / google doc

### This pull request is ready to code review when

- [x] Automated tests are updated (and all tests are passing)
- [x] New automated test cases are documented above
- [x] Pull request has been labeled, if applicable with feature, content, bug,
      tests, refactor
- [x] Associated OpenAPI documentation has been updated
- [x] The experience passes a basic manual accessibility audit (keyboard nav,
      screenreader, text scaling) OR an exemption is documented

### This pull request is ready to test when

- [ ] Code has been reviewed by someone other than the original author

### This pull request is ready to review when the QA has

- [ ] Verified the functionality related to the change
- [ ] Verified that the change works with Narrator on Windows
- [ ] Verified that the change works with VoiceOver on Mac
- [ ] Verified all updated pages with the WAVE tool
- [ ] Verified tab and keyboard navigation functionality

### This pull request can be merged when

- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by thetif — APPROVED** [review]
great work!

**Review by thetif — APPROVED** [review]
great work!

**Comment by jeromeleecms** [comment]
Waiting for backend tests to be resolved before we put this in.

**Comment by jeromeleecms** [comment]
@tbolt Should I be expecting the links to work for sections that worked previously? The sidebar looks great with some links to previously functioning sections crashing the system (examples: Results of previous activities, Cost Allocation, and some budget tables) ... if that's the expected behavior, than looks good!

**Review by jeromeleecms — APPROVED** [review]
Thanks for the updates/details. This looks good to me then! I'll let @stephanieboydcms have an opportunity to take a look as well.

**Review by stephanieboydcms — APPROVED** [review]
Everything looks great!  Thanks to everyone on their hard work

**Pull request merged**
