### PR TITLE
updated key state personnel

### LINKED ISSUE #4554: [Feature] Update Read-Only View for MMIS changes to Key State Personnel
### Description and related issues
Update the Key State Personnel Read-Only component to display the new Key State Personnel data to match the Figma.

**Changes to Key State Personnel:**
* Add Total Medicaid Computable to section
* Add Medicaid Share to section
* Add Federal Share to section

### Mockups or link to Figma
Data state - https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=3867%3A27442&t=irHudAE6PbwrblAu-1
Empty state - https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=4177%3A19459&t=irHudAE6PbwrblAu-1

### Acceptance criteria

- [ ] create stories for data and empty state
- [ ] update Key State Personnel read-only component to display differently for HITECH and MMIS
- [ ] create MMIS version of read-only component to match the figma

| Given | When | Then | Covered |
| ----- | ---- | ---- | ------- |
|a HITECH APD| On the export view | Key State Personnel section should be the same and not have any MMIS updates |         |
|a MMIS APD| On the export view (use Chromatic if page crashes) | Key State Personnel section should match the data in the Key State Personnel page |         |
|a MMIS APD| Key State Personnel data is changed (added KP/deleted KP/edited KP) | Key State Personnel section should match the changed data |        
|a MMIS APD| Key State Personnel data is blank | Key State Personnel section should match the empty state |

### PR DESCRIPTION
**Pull request by thetif**
Resolves #4554 

### Description
Updated the Key State Personnel read-only to match Figma updates. Added row for key personnel total medicaid costs for MMIS.

### Automated test cases written

| Given | When | Then | Type (jest, tap, cypress) |
| ----- | ---- | ---- | ------------------------- |
| a HITECH key person | on the export view | show FFY X Cost row |  jest |
| a MMIS key person | on the export view | show FFY Cost row and Total Computable Medicaid Cost row | jest |
| a key person | on the export view | show the person's name, position, and email | jest |
| a medicaid director | on the export view | show the director's name, email, and phone number | jest |
| an empty medicaid director | on the export view | show "No Medicaid director was provided" | jest |
| a medicaid office | on the export view | show the address | jest |
| an empty medicaid office | on the export view | show "No Medicaid office was provided" | jest |
| an empty medicaid director and medicaid office | on the export view | show "No Medicaid director and corresponding Medicaid office address was provided | jest |

### Steps to manually verify this change

1. open a HITECH APD
2. go to Export and Submit page
3. click Continue to Review
4. scroll to Key State Personnel section

You won't be able to view the MMIS APD, but you can verify it on [storybook](https://www.chromatic.com/builds?appId=61d5b948cf6f17003a12bf77&branch=tforkner/4554-update-key-state-personnel)

### This pull request is ready to code review when

- [x] Automated tests are updated (and all tests are passing)
- [x] New automated test cases are documented above
- [x] Pull request has been labeled, if applicable with feature, content, bug,
      tests, refactor

### This pull request is ready to test when

- [ ] Code has been reviewed by someone other than the original author

### This pull request is ready to review when the QA has

- [ ] Verified the functionality related to the change
- [ ] Verified that the change works with Narrator on Windows
- [ ] Verified that the change works with VoiceOver on Mac
- [ ] Verified all updated pages with the WAVE tool
- [ ] Verified tab and keyboard navigation functionality

### This pull request can be merged when

- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by Sun-Mountain — APPROVED** [review]
🚀

**Comment by mirano-darren** [comment]
Looks good to me! Saved the storybook approving for design 😄 
| Given | When | Then | Covered |
| ----- | ---- | ---- | ------- |
|a HITECH APD| On the export view | Key State Personnel section should be the same and not have any MMIS updates | ✅  |
|a MMIS APD| On the export view (use Chromatic if page crashes) | Key State Personnel section should match the data in the Key State Personnel page | ✅  |
|a MMIS APD| Key State Personnel data is changed (added KP/deleted KP/edited KP) | Key State Personnel section should match the changed data | 🟨 Cannot test since page still crashes |
|a MMIS APD| Key State Personnel data is blank | Key State Personnel section should match the empty state | ✅

**Review by mirano-darren — APPROVED** [review]

**Review by SGilliamA1M — APPROVED** [review]
Changes look great! Thanks

**Review by stephanieboydcms — APPROVED** [review]
This looks to go

**Pull request merged**
