### PR TITLE
Tforkner/4376 upgrades

### LINKED ISSUE #4376: [Maintenance] Update node
### Description and related issues
There is a security issue with our current version of node on docker (16.16.0-alpine3.15). We should upgrade to 16.18.0. We should also switch to using the bullseye-slim image because it has fewer unnecessary modules installed. 

### This task is done when…

- [ ] upgrade the front and backend to use 16.18.0-bullseye-slim
- [ ] upgrade application to use 16.18.0

### PR DESCRIPTION
**Pull request by thetif**
Resolves #4376 

### Description
Upgraded node from 16.16.0 to 16.19.0. Upgraded babel, eslint, and all of the patch updates.

This can't be tested in Preview until Bill updates the AMI.

### Significant changes or possible side effects
I had to make some changes to the APD New page because the Create New APD button wasn't disabling every time it needed to.

Also the update to core-axe came with a [new rule](https://dequeuniversity.com/rules/axe/4.6/empty-table-header?application=axeAPI). You aren't allowed to have an empty <th></th>. In the Quarterly Federal Share and Estimated Quarterly Incentive Payments tables, were using aria-hidden on the first header cell and axe was flagging that. I took off the aria-hidden and it's passing now.

### This pull request is ready to code review when

- [x] Automated tests are updated (and all tests are passing)
- [x] Pull request has been labeled, if applicable with feature, content, bug,
      tests, refactor

### This pull request is ready to test when

- [ ] Code has been reviewed by someone other than the original author

### This pull request is ready to review when the QA has

- [ ] Verified the functionality related to the change
- [ ] Verified that the change works with Narrator on Windows
- [ ] Verified that the change works with VoiceOver on Mac
- [ ] Verified all updated pages with the WAVE tool
- [ ] Verified tab and keyboard navigation functionality

### This pull request can be merged when

- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by tbolt — APPROVED** [review]
Looks good

**Review by amyd11 — APPROVED** [review]
Looks good. Thanks for adding in all those id's throughout the code.

**Question (non-blocking):** When creating an APD, the name is not a required field- should that be required as well?

**Review by Sun-Mountain — APPROVED** [review]
🚀

**Review by mirano-darren — APPROVED** [review]
LGTM! Bug ticket with create new APD page documented in #4502

**Review by tbolt — APPROVED** [review]

**Review by jeromeleecms — APPROVED** [review]
Good pick up on the APD switching bug (but that was already there). Looks good to move forward - also approved in Chromatic.

**Pull request merged**
