### PR TITLE
Tbolt/4559 update apd overview mmis read only

### LINKED ISSUE #4559: [Feature] Update Read-Only View for MMIS changes to APD Overview
### Description and related issues
Update the APD Overview section of the export view to display the new APD Overview information.

**Changes to APD Overview:**
* Add Program Funding Source
* Add APD Type
* Add Update Type
* Add Medicaid Business Area
* Add branching style only when other is selected

### Mockups or link to Figma

Data view - https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=3674%3A23279&t=RAQ43sFg8BtVc5qU-1
Empty view -https://www.figma.com/file/hJpKHKU6fz5J0Z7fisSwa2/eAPD-MMIS-2022?node-id=3725%3A25149&t=2Pbpmc5Nooy0Cy7r-1

### Acceptance criteria

- [x] create stories for data and empty state
- [x] update APD overview read-only component to display differently for HITECH and MMIS
- [x] create MMIS version of read-only component to match the figma

### Testing criteria

| Given | When | Then | Covered |
| ----- | ---- | ---- | ------- |
|a HITECH APD| On the export view | APD Overview section should be the same and not have any MMIS updates |         |
|a MMIS APD| On the export view (use Chromatic if page crashes) | APD Overview section should match the data in the APD Overview page |         |
|a MMIS APD| APD Overview data is changed (added/deleted/edited) | APD Overview section should match the changed data |        
|a MMIS APD| APD Overview data is blank | APD Overview section should match the empty state |

### PR DESCRIPTION
**Pull request by tbolt**
Resolves #4559 

### Description
Updates APD Overview section in the export/read-only view for MMIS APDs

### Chromatic Link
https://www.chromatic.com/pullrequest?appId=61d5b948cf6f17003a12bf77&number=4601

### Significant changes or possible side effects
No side effects

### Automated test cases written

| Given | When | Then | Type (jest, tap, cypress) |
| ----- | ---- | ---- | ------------------------- |
| a HITECH apd | no values are entered in APD Overview | renders correctly | jest |
| a HITECH apd | valid data is entered in APD Overview | renders correctly | jest |
| a MMIS apd | no values are entered in APD Overview | renders correctly | jest |
| a MMIS apd | valid data is entered in APD Overview | renders correctly | jest |

### Steps to manually verify this change

1. Login and view a HITECH apd
2. Verify no changes are present in APD Overview section of read-only/export view
3. Use chromatic to see the changes for MMIS
4. Verify design updates are present in APD Overview section of read-only/export view for MMIS

### This pull request is ready to code review when

- [x] Automated tests are updated (and all tests are passing)
- [x] New automated test cases are documented above
- [x] Chromatic link added above
- [x] Pull request has been labeled, if applicable with feature, content, bug,
      tests, refactor
- [x] Associated OpenAPI documentation has been updated
- [ ] The experience passes a basic manual accessibility audit (keyboard nav,
      screenreader, text scaling) OR an exemption is documented

### This pull request is ready to test when

- [ ] Code has been reviewed by someone other than the original author

### This pull request is ready to review when QA has

- [ ] Verified the functionality related to the change
- [ ] Verified that the change works with Narrator on Windows
- [ ] Verified that the change works with VoiceOver on Mac
- [ ] Verified all updated pages with the WAVE tool
- [ ] Verified tab and keyboard navigation functionality

### This pull request can be merged when

- [ ] Design has approved the experience
- [ ] Product has approved the experience

### CODE REVIEW

**Review by Sun-Mountain — APPROVED** [review]
🚀

**Review by mirano-darren — APPROVED** [review]
Looks good to me!
| Given | When | Then | Covered |
| ----- | ---- | ---- | ------- |
|a HITECH APD| On the export view | APD Overview section should be the same and not have any MMIS updates |     ✅     |
|a MMIS APD| On the export view (use Chromatic if page crashes) | APD Overview section should match the data in the APD Overview page |   ✅       |
|a MMIS APD| APD Overview data is changed (added/deleted/edited) | APD Overview section should match the changed data |    🟨 Cannot test due to export view page crashing    |
|a MMIS APD| APD Overview data is blank | APD Overview section should match the empty state |    ✅ |

**Review by SGilliamA1M — APPROVED** [review]
Changes look great! MMIS read-only view crashed in the app but was able to verify in Chromatic.

**Comment by jeromeleecms** [comment]
@tbolt @mirano-darren The MMIS APD read only/export view don't work yet right? The manual testing says to open an MMIS IAPD and view the export (which right now puts my in a blank screen).

**Comment by tbolt** [comment]
@jeromeleecms thats right, ignore that part of the testing step. You can view chromatic to see the updates though.

**Review by jeromeleecms — APPROVED** [review]
Thanks @tbolt - looks good!

**Pull request merged**
